### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by scotrod** [vantezzen/wrapped#6]
After installing all the dependencies on ubuntu server using `npm install` and `npm run dev` to run the server, I get the following error:
```
user@machine:~/scripts/wrapped$ npm run dev

> tiktok-wrapped@0.1.0 dev
> next dev

/home/user/scripts/wrapped/node_modules/next/dist/cli/next-dev.js:256
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/user/scripts/wrapped/node_modules/next/dist/lib/commands.js:15:30)
    at Object.<anonymous> (/home/user/scripts/wrapped/node_modules/next/dist/bin/next:150:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**Comment by vantezzen** [comment]
Thank you for reporting this - it looks like you are using an old version of NodeJS? Can you make sure you are using 20 LTS or later?
